import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { cn } from '../../utils/cn';
const Input = React.forwardRef(({ className, type, label, error, helpText, leftIcon, rightIcon, id, ...props }, ref) => {
    const inputId = id || `input-${Math.random().toString(36).substr(2, 9)}`;
    return (_jsxs("div", { className: "w-full", children: [label && (_jsx("label", { htmlFor: inputId, className: "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2", children: label })), _jsxs("div", { className: "relative", children: [leftIcon && (_jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx("span", { className: "text-gray-500 dark:text-gray-400 sm:text-sm", children: leftIcon }) })), _jsx("input", { type: type, id: inputId, className: cn('flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50', leftIcon && 'pl-10', rightIcon && 'pr-10', error && 'border-red-500 focus-visible:ring-red-500', className), ref: ref, ...props }), rightIcon && (_jsx("div", { className: "absolute inset-y-0 right-0 pr-3 flex items-center", children: _jsx("span", { className: "text-gray-500 dark:text-gray-400 sm:text-sm", children: rightIcon }) }))] }), error && (_jsx("p", { className: "mt-1 text-sm text-red-600 dark:text-red-400", children: error })), helpText && !error && (_jsx("p", { className: "mt-1 text-sm text-gray-500 dark:text-gray-400", children: helpText }))] }));
});
Input.displayName = 'Input';
export { Input };
