import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Card, CardContent, Button, Badge } from '../ui';
import { Inbox, Send, Archive, Trash2, Star, Edit, Shield, Settings, User, LogOut } from 'lucide-react';
const defaultFolders = [
    { id: 'inbox', name: 'Inbox', icon: Inbox, count: 12 },
    { id: 'sent', name: 'Sent', icon: Send, count: 0 },
    { id: 'starred', name: 'Starred', icon: Star, count: 3 },
    { id: 'archive', name: 'Archive', icon: Archive, count: 45 },
    { id: 'trash', name: 'Trash', icon: Trash2, count: 2 }
];
const securityLevels = [
    { level: 'Level 1', name: 'Standard', color: 'bg-green-500', count: 8 },
    { level: 'Level 2', name: 'Enhanced', color: 'bg-yellow-500', count: 3 },
    { level: 'Level 3', name: 'Classified', color: 'bg-orange-500', count: 1 },
    { level: 'Level 4', name: 'Top Secret', color: 'bg-red-500', count: 0 }
];
export const Sidebar = ({ onComposeClick, onFolderSelect, selectedFolder = 'inbox', user, onLogout, folders, collapsed = false, onToggleCollapse, quantumKeysAvailable, systemStatus }) => {
    const effectiveFolders = folders && folders.length > 0 ? folders : defaultFolders;
    const statusColor = systemStatus === 'critical' ? 'text-red-600 dark:text-red-400' : systemStatus === 'degraded' ? 'text-yellow-600 dark:text-yellow-400' : 'text-green-600 dark:text-green-400';
    if (collapsed) {
        return (_jsxs("div", { className: "w-16 bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 flex flex-col items-center py-4 gap-4", children: [_jsx("button", { onClick: onToggleCollapse, className: "w-10 h-10 rounded-lg flex items-center justify-center bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:opacity-90", children: _jsx(Edit, { className: "w-4 h-4" }) }), effectiveFolders.map(f => (_jsx("button", { onClick: () => onFolderSelect?.(f.id), title: f.name, className: `w-10 h-10 rounded-lg flex items-center justify-center text-sm transition-colors ${selectedFolder === f.id
                        ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-300'
                        : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'}`, children: React.createElement(f.icon || Inbox, { className: 'w-4 h-4' }) }, f.id))), _jsx("div", { className: "mt-auto pb-2", children: _jsx("button", { onClick: onToggleCollapse, className: "text-xs text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200", children: "\u25B6" }) })] }));
    }
    return (_jsxs("div", { className: "w-64 bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 flex flex-col", children: [user && (_jsx("div", { className: "p-4 border-b border-gray-200 dark:border-gray-700", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-gradient-to-r from-blue-500 to-purple-600 flex items-center justify-center", children: user.avatar ? (_jsx("img", { src: user.avatar, alt: user.name, className: "w-full h-full rounded-full" })) : (_jsx(User, { className: "w-5 h-5 text-white" })) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-medium text-gray-900 dark:text-white truncate", children: user.name }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400 truncate", children: user.email })] })] }) })), _jsx("div", { className: "p-4", children: _jsxs(Button, { onClick: onComposeClick, className: "w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700", children: [_jsx(Edit, { className: "w-4 h-4 mr-2" }), "Compose"] }) }), _jsxs("div", { className: "flex-1 overflow-auto", children: [_jsxs("div", { className: "px-4 pb-4", children: [_jsx("h3", { className: "text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2", children: "Folders" }), _jsx("nav", { className: "space-y-1", children: effectiveFolders.map((folder) => {
                                    const Icon = folder.icon || Inbox;
                                    const isSelected = selectedFolder === folder.id;
                                    return (_jsxs("button", { onClick: () => onFolderSelect?.(folder.id), className: `w-full flex items-center justify-between px-3 py-2 text-sm rounded-lg transition-colors ${isSelected
                                            ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300'
                                            : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Icon, { className: "w-4 h-4" }), _jsx("span", { children: folder.name })] }), folder.count && folder.count > 0 && (_jsx(Badge, { variant: "secondary", className: "text-xs", children: folder.count }))] }, folder.id));
                                }) })] }), _jsxs("div", { className: "px-4 pb-4", children: [_jsx("h3", { className: "text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2", children: "Security Levels" }), _jsx("div", { className: "space-y-2", children: securityLevels.map((level) => (_jsxs("div", { className: "flex items-center justify-between px-3 py-2 text-sm rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 cursor-pointer", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-2 h-2 rounded-full ${level.color}` }), _jsx("span", { className: "text-gray-700 dark:text-gray-300", children: level.name })] }), level.count > 0 && (_jsx(Badge, { variant: "secondary", className: "text-xs", children: level.count }))] }, level.level))) })] }), _jsx("div", { className: "px-4 pb-4", children: _jsx(Card, { className: "bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-900/20 dark:to-blue-900/20 border-green-200 dark:border-green-800", children: _jsxs(CardContent, { className: "p-3 space-y-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Shield, { className: "w-4 h-4 text-green-600 dark:text-green-400" }), _jsx("span", { className: "text-xs font-medium text-green-700 dark:text-green-300", children: "Quantum Status" })] }), _jsxs("div", { className: "flex justify-between text-xs", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Active Keys:" }), _jsx("span", { className: "font-medium text-green-600 dark:text-green-400", children: quantumKeysAvailable ?? 6400 })] }), systemStatus && (_jsxs("div", { className: "flex justify-between text-xs", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "KME Status:" }), _jsx("span", { className: `font-medium ${statusColor}`, children: systemStatus })] }))] }) }) })] }), _jsx("div", { className: "p-4 border-t border-gray-200 dark:border-gray-700", children: _jsxs("div", { className: "space-y-2", children: [_jsxs(Button, { variant: "ghost", size: "sm", className: "w-full justify-start", children: [_jsx(Settings, { className: "w-4 h-4 mr-2" }), "Settings"] }), user && (_jsxs(Button, { variant: "ghost", size: "sm", className: "w-full justify-start text-red-600 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-900/20", onClick: onLogout, children: [_jsx(LogOut, { className: "w-4 h-4 mr-2" }), "Sign Out"] }))] }) })] }));
};
export default Sidebar;
